### ISSUE TITLE
setrounding not working with constants

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaIntervals/SetRounding.jl#14]
This package doesn't seem to be working for me:
```julia
julia> using SetRounding

julia> setrounding(Float64, RoundUp) do
                                1.0/3.0
                            end
0.3333333333333333

julia> setrounding(Float64, RoundDown) do
                                1.0/3.0
                            end
0.3333333333333333
```
Though IntervalArithmetic.jl is working fine...

**Comment by dlfivefifty** [comment]
Oh wait, the issue seems to be hard-coded constants presumably reduced at compile time. Doing the following works:
```julia
julia> setrounding(Float64, RoundDown) do
       x/y
       end
0.3333333333333333

julia> setrounding(Float64, RoundUp) do
       x/y
       end
0.33333333333333337
```
Or alternatively:
```julia
julia> setrounding(Float64, RoundUp)
0

julia> 1.0/3.0
0.33333333333333337
```

Probably there's nothing that can be done for this...

**Comment by dpsanders** [comment]
Yes exactly.

IntervalArithmetic.jl no longer uses this package by default. It uses RoundingEmulator.jl to get correct rounding.

The easiest and fastest solution, though, is to just use prevfloat and nextfloat if you don't care about getting the *closest* float all the time. That's one of the modes that IntervalArithmetic.jl allows.

**Comment by dpsanders** [comment]
The problem is that LLVM did not understand about rounding modes so did premature optimization. Apparently there's now some way to control it, but given the other available options, and the fact that controlling a global hardware rounding mode is not threadsafe (and is slow!) the other options seem better.

**Comment by dlfivefifty** [comment]
It's for a lecture on Floating-point arithmetic so using something that's not the closest float defeats the point... I decided just doing
```julia
x = 1f0
setrounding(Float32, RoundUp) do
    x/3
end
```
is clean enough. 

PS My week 1 problem sheet question is "complete this implementation of Interval arithmetic and compute e to 1000 digits with precise error bounds." Should be fun 😄

**Comment by dpsanders** [comment]
That is a great homework :) 

`setrounding` should work fine for `BigFloat`, since it's all in software via MPFR. This package is only for `Float64` where you actually need to change the hardware rounding mode. 

(This [Float64 rounding] used to be in Base Julia, but was removed in 1.0 (?) exactly due to the issue that you are highlighting here.)

https://github.com/matsueushi/RoundingEmulator.jl does correct rounding for Float64 in software, without actually manipulating the hardware rounding mode, by using error-free arithmetic (see e.g. https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl)

**Comment by dpsanders** [comment]
I don't necessarily think that it defeats the point, since the point is that doing correct rounding is actually quite hard ;) But that doing *directed* rounding is easy, if you don't care about getting the *closest* float always.

**Comment by dlfivefifty** [comment]
The _point_ of the lecture is "this is how the computer arithmetic works". So doing "directed rounding" is not an accurate representation....
